version: '3.9'

services:
  web:
    build: .
    container_name: grafo_web
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgis/postgis:13-3.1
    container_name: grafo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grafos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  alembic:
    build: .
    container_name: grafo_alembic
    command: alembic upgrade head
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data:
