"""create grafos, nos and arestas tables

Revision ID: b8827d7b9929
Revises: 21ca00ad0ec9
Create Date: 2024-06-02 16:47:31.806484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'b8827d7b9929'
down_revision: Union[str, None] = '21ca00ad0ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grafos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grafos_id'), 'grafos', ['id'], unique=False)
    op.create_index(op.f('ix_grafos_nome'), 'grafos', ['nome'], unique=False)
    op.create_table('nos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grafo_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('coordenada', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['grafo_id'], ['grafos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_index('idx_nos_coordenada', 'nos', ['coordenada'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_nos_id'), 'nos', ['id'], unique=False)
    op.create_index(op.f('ix_nos_nome'), 'nos', ['nome'], unique=False)
    op.create_table('arestas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grafo_id', sa.UUID(), nullable=False),
    sa.Column('no_origem_id', sa.UUID(), nullable=False),
    sa.Column('no_destino_id', sa.UUID(), nullable=False),
    sa.Column('linha', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['grafo_id'], ['grafos.id'], ),
    sa.ForeignKeyConstraint(['no_destino_id'], ['nos.id'], ),
    sa.ForeignKeyConstraint(['no_origem_id'], ['nos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_index('idx_arestas_linha', 'arestas', ['linha'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_arestas_id'), 'arestas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_arestas_id'), table_name='arestas')
    op.drop_index('idx_arestas_linha', table_name='arestas', postgresql_using='gist')
    op.drop_table('arestas')
    op.drop_index(op.f('ix_nos_nome'), table_name='nos')
    op.drop_index(op.f('ix_nos_id'), table_name='nos')
    op.drop_index('idx_nos_coordenada', table_name='nos', postgresql_using='gist')
    op.drop_table('nos')
    op.drop_index(op.f('ix_grafos_nome'), table_name='grafos')
    op.drop_index(op.f('ix_grafos_id'), table_name='grafos')
    op.drop_table('grafos')
    # ### end Alembic commands ###
